#!/usr/bin/env python

import sys

import cbfireeyebridge.bridge
import cbfireeyebridge.version

if __name__ == "__main__":
    name = "carbonblack_fireeye_bridge"
    daemon = cbfireeyebridge.bridge.CarbonBlackFireEyeBridge(name, "/etc/cb/integrations/carbonblack_fireeye_bridge/carbonblack_fireeye_bridge.conf")
    if len(sys.argv) == 2:
        if 'start' == sys.argv[1]:
            daemon.start()
        elif 'stop' == sys.argv[1]:
            daemon.stop()
        elif 'restart' == sys.argv[1]:
            daemon.restart()
        elif 'version' == sys.argv[1]:
            print "%s - version %s" % (name, cbfireeyebridge.version.__version__)
        else:
            print "Unknown command: %s" % sys.argv[1]
            sys.exit(2)

    else:
        print "Usage: %s start|stop|restart|version" % sys.argv[0]
        sys.exit(2)

